name: Eggs
main: com.leontg77.eggs.Main
version: 1.0
author: LeonTG77
description: When you throw an egg, a random mob will spawn where it lands. This includes enderdragons and withers. When you kill a chicken, there is a 5% chance of it dropping an egg.

commands:
    eggs:
        description: Enable or disable the plugin features.